### ISSUE TITLE
EECS UC Berkeley 只有 EE 部分，缺少 CS 部分

### ISSUE THREAD

**Issue by PearlyWave** [MuggleWei/learning_compass#1]
https://hkn.eecs.berkeley.edu/courseguides 的下半部分 COURSE MAP是 CS 的部分

**Comment by MuggleWei** [comment]
因为上午做好EE部分之后，下午做其他事去了，准备晚上补全。
谢谢你的issue

**Comment by MuggleWei** [comment]
已在 EECS 学科页面中，添加了UC Berkeley的CS部分课程   
https://github.com/MuggleWei/learning_compass/commit/feed8e86f5ced09013fab03379e1eba70a79a26b

当前EECS中，UC Berkeley的每门课程对应的页面和链接暂缺，之后会慢慢补全
